// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260308105156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            Description = "",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            Description = "",
                            Name = "Smartphone",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            Description = "",
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            Description = "",
                            Name = "Smartwatch",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Description = "",
                            Name = "Tablet",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            Description = "",
                            Name = "Camera",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "",
                            Description = "",
                            Name = "Printer",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "",
                            Description = "",
                            Name = "Monitor",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 9,
                            Category = "",
                            Description = "",
                            Name = "Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 10,
                            Category = "",
                            Description = "",
                            Name = "Mouse",
                            Price = 49.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
